# These are supported funding model platforms

github: alexnguyen03 
ko_fi: alexnguyen03 # Replace with a single Ko-fi username
custom: ['https://paypal.me/alexnguyeen03']  # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
