import { wailsGateway } from '../platform/app-api/wailsGateway';

export const ExecuteQuery = (tabId: string, query: string) => wailsGateway.ExecuteQuery(tabId, query);
export const CancelQuery = (tabId: string) => wailsGateway.CancelQuery(tabId);
export const ExplainQuery = (tabId: string, query: string, analyze: boolean) => wailsGateway.ExplainQuery(tabId, query, analyze);
export const ExecuteUpdateSync = (sql: string) => wailsGateway.ExecuteUpdateSync(sql);
export const FetchMoreRows = (tabId: string, offset: number) => wailsGateway.FetchMoreRows(tabId, offset);
export const StartFetchTotalRowCount = (tabId: string, requestId: number) => wailsGateway.StartFetchTotalRowCount(tabId, requestId);
export const FetchTotalRowCount = (tabId: string) => wailsGateway.FetchTotalRowCount(tabId);
export const FormatSQL = (query: string, driver: string) => wailsGateway.FormatSQL(query, driver);
export const CompareQueries = (original: string, modified: string) => wailsGateway.CompareQueries(original, modified);
export const ExportCSV = (columns: string[], rows: unknown[]) => wailsGateway.ExportCSV(columns, rows);
export const ExportAllCSV = (tabId: string, selectedColumns: string[]) => wailsGateway.ExportAllCSV(tabId, selectedColumns);
export const ExportJSON = (columns: string[], rows: unknown[]) => wailsGateway.ExportJSON(columns, rows);
export const ExportAllJSON = (tabId: string, selectedColumns: string[]) => wailsGateway.ExportAllJSON(tabId, selectedColumns);
export const ExportSQLInsert = (columns: string[], rows: unknown[], tableName: string) => wailsGateway.ExportSQLInsert(columns, rows, tableName);
export const ExportAllSQLInsert = (tabId: string, tableName: string, selectedColumns: string[]) => wailsGateway.ExportAllSQLInsert(tabId, tableName, selectedColumns);
export const BeginTransaction = () => wailsGateway.BeginTransaction();
export const CommitTransaction = () => wailsGateway.CommitTransaction();
export const RollbackTransaction = () => wailsGateway.RollbackTransaction();
export const GetTransactionStatus = () => wailsGateway.GetTransactionStatus();
