import {
    AddPrimaryKey,
    AddTableColumn,
    AlterTableColumn,
    BeginTransaction,
    CancelQuery,
    CheckForUpdates,
    ClearHistory,
    CommitTransaction,
    CompareQueries,
    Connect,
    ConnectProjectEnvironment,
    CreateCheckConstraint,
    CreateIndex,
    CreateUniqueConstraint,
    DropCheckConstraint,
    DropForeignKey,
    DropPrimaryKey,
    DropUniqueConstraint,
    GetCheckConstraints,
    GetForeignKeys,
    GetPrimaryKey,
    GetUniqueConstraints,
    CreateProject,
    CreateTable,
    DeleteBookmark,
    DeleteConnection,
    DeleteProject,
    DeleteScript,
    DeleteTemplate,
    Disconnect,
    DisableGitTracking,
    DropIndex,
    DropObject,
    DropObjectAdvanced,
    DropTableColumn,
    ExecuteQuery,
    ExecuteUpdateSync,
    ExplainQuery,
    EnableGitTracking,
    ExportAllCSV,
    ExportAllJSON,
    ExportAllSQLInsert,
    ExportCSV,
    ExportConnectionPackage,
    ExportJSON,
    ExportSQLInsert,
    FetchDatabaseSchema,
    FetchMoreRows,
    FetchTableColumns,
    FetchTableRelationships,
    FetchTotalRowCount,
    ForceQuit,
    FormatSQL,
    GetBookmarks,
    GetConnectionStatus,
    GetActiveProject,
    GetDefaultProjectStorageRoot,
    GetGitCommitDiff,
    GetCommitFileDiffs,
    GetGitPendingChanges,
    GetGitTrackingStatus,
    GetHistory,
    GetIndexes,
    GetPreferences,
    GetProject,
    GetScriptContent,
    GetScripts,
    GetTableDDL,
    GetTransactionStatus,
    ImportConnectionPackage,
    ListProjects,
    ListGitTimeline,
    ManualGitCommit,
    LoadConnections,
    LoadDatabasesForProfile,
    LoadTemplates,
    OpenProject,
    OpenProjectFromDirectory,
    PickDirectory,
    Reconnect,
    RollbackTransaction,
    RestoreGitCommit,
    RunGitTrackingMigration,
    SCCommit,
    SCGetFileDiffs,
    SCGetHistory,
    SCGetStatus,
    SCGetWorkingFileDiff,
    SCListBranches,
    SCCheckoutBranch,
    SCCreateBranch,
    SCCreateBranchFrom,
    SCCheckoutDetached,
    SCInitRepo,
    SCStageAll,
    SCStageFile,
    SCUnstageFile,
    SaveBookmark,
    SaveConnection,
    SaveProject,
    SaveScript,
    SaveTemplate,
    SetPreferences,
    SnapshotStoredProcedures,
    SwitchDatabase,
    TestConnection,
    TruncateTable,
    CreateForeignKey,
    UpdateForeignKey,
} from '../../../wailsjs/go/app/App';
import type { AppApiGateway, ConnectionRuntimeState } from './types';
import type { ConnectionProfile } from '../../types/connection';
import { CONNECTION_STATUS } from '../../lib/constants';

function normalizeRuntimeConnectionStatus(status: unknown): ConnectionRuntimeState['status'] {
    if (status === CONNECTION_STATUS.CONNECTED || status === CONNECTION_STATUS.CONNECTING || status === CONNECTION_STATUS.DISCONNECTED || status === CONNECTION_STATUS.ERROR) {
        return status as ConnectionRuntimeState['status'];
    }
    return CONNECTION_STATUS.DISCONNECTED;
}

function toConnectionProfile(raw: unknown): ConnectionProfile | null {
    if (!raw || typeof raw !== 'object') return null;
    const source = raw as Record<string, unknown>;

    if (typeof source.name !== 'string' || typeof source.driver !== 'string') {
        return null;
    }

    return {
        name: source.name,
        driver: source.driver,
        host: typeof source.host === 'string' ? source.host : '',
        port: typeof source.port === 'number' ? source.port : 0,
        db_name: typeof source.db_name === 'string' ? source.db_name : '',
        username: typeof source.username === 'string' ? source.username : '',
        password: typeof source.password === 'string' ? source.password : '',
        ssl_mode: typeof source.ssl_mode === 'string' ? source.ssl_mode : '',
        connect_timeout: typeof source.connect_timeout === 'number' ? source.connect_timeout : 10,
        save_password: source.save_password === true,
        encrypt_password: source.encrypt_password === true,
        show_all_schemas: source.show_all_schemas === true,
        trust_server_cert: source.trust_server_cert === true,
    };
}

function toConnectionRuntimeState(raw: unknown): ConnectionRuntimeState {
    if (!raw || typeof raw !== 'object') {
        return { status: CONNECTION_STATUS.DISCONNECTED, profile: null };
    }
    const source = raw as Record<string, unknown>;

    return {
        status: normalizeRuntimeConnectionStatus(source.status),
        profile: toConnectionProfile(source.profile),
    };
}

export const wailsGateway: AppApiGateway = {
    Connect,
    Disconnect,
    Reconnect,
    SwitchDatabase,
    LoadConnections,
    LoadDatabasesForProfile,
    SaveConnection,
    DeleteConnection,
    ImportConnectionPackage,
    ExportConnectionPackage,
    TestConnection,
    GetConnectionStatus: async () => toConnectionRuntimeState(await GetConnectionStatus()),

    ExecuteQuery,
    CancelQuery,
    ExplainQuery,
    ExecuteUpdateSync,
    FetchMoreRows,
    FetchTotalRowCount,
    FormatSQL,
    CompareQueries,
    ExportCSV,
    ExportAllCSV,
    ExportJSON,
    ExportAllJSON,
    ExportSQLInsert,
    ExportAllSQLInsert,

    BeginTransaction,
    CommitTransaction,
    RollbackTransaction,
    GetTransactionStatus,

    FetchDatabaseSchema,
    FetchTableColumns,
    FetchTableRelationships,
    CreateTable,
    DropObject,
    DropObjectAdvanced,
    TruncateTable,
    GetTableDDL,
    AlterTableColumn,
    AddTableColumn,
    DropTableColumn,
    GetIndexes,
    CreateIndex,
    DropIndex,
    GetCheckConstraints,
    CreateCheckConstraint,
    DropCheckConstraint,
    GetUniqueConstraints,
    CreateUniqueConstraint,
    DropUniqueConstraint,
    GetPrimaryKey,
    AddPrimaryKey,
    DropPrimaryKey,
    GetForeignKeys,
    CreateForeignKey,
    UpdateForeignKey,
    DropForeignKey,

    GetPreferences,
    SetPreferences,
    CheckForUpdates,

    GetHistory,
    ClearHistory,
    LoadTemplates,
    SaveTemplate,
    DeleteTemplate,
    GetScripts,
    GetScriptContent,
    SaveScript,
    DeleteScript,
    GetBookmarks,
    SaveBookmark,
    DeleteBookmark,
    EnableGitTracking,
    DisableGitTracking,
    GetGitTrackingStatus,
    ListGitTimeline,
    GetGitCommitDiff,
    GetCommitFileDiffs,
    ManualGitCommit,
    GetGitPendingChanges,
    RestoreGitCommit,
    SCCommit,
    SCGetFileDiffs,
    SCGetHistory,
    SCGetWorkingFileDiff,
    SCListBranches,
    SCCheckoutBranch,
    SCCreateBranch,
    SCCreateBranchFrom,
    SCCheckoutDetached,
    SCGetStatus: async () => {
        const result = await SCGetStatus();
        return result as import('./types').SCStatus;
    },
    SCInitRepo,
    SCStageAll,
    SCStageFile,
    SCUnstageFile,
    SnapshotStoredProcedures,
    RunGitTrackingMigration,

    ForceQuit,
    ConnectProjectEnvironment,

    ListProjects,
    GetProject,
    CreateProject,
    SaveProject,
    DeleteProject,
    OpenProject,
    OpenProjectFromDirectory,
    GetDefaultProjectStorageRoot,
    PickDirectory,
    GetActiveProject,
};
