import {
    AddTableColumn,
    AlterTableColumn,
    BeginTransaction,
    CancelQuery,
    CheckForUpdates,
    ClearHistory,
    CommitTransaction,
    CompareQueries,
    Connect,
    ConnectProjectEnvironment,
    CreateIndex,
    CreateTable,
    DeleteBookmark,
    DeleteScript,
    DeleteTemplate,
    Disconnect,
    DropIndex,
    DropObject,
    DropTableColumn,
    ExecuteQuery,
    ExecuteUpdateSync,
    ExplainQuery,
    ExportCSV,
    ExportJSON,
    ExportSQLInsert,
    FetchDatabaseSchema,
    FetchMoreRows,
    FetchTableColumns,
    FetchTableRelationships,
    FetchTotalRowCount,
    ForceQuit,
    FormatSQL,
    GetBookmarks,
    GetConnectionStatus,
    GetHistory,
    GetIndexes,
    GetPreferences,
    GetScriptContent,
    GetScripts,
    GetTableDDL,
    GetTransactionStatus,
    LoadConnections,
    LoadDatabasesForProfile,
    LoadTemplates,
    Reconnect,
    RollbackTransaction,
    SaveBookmark,
    SaveConnection,
    SaveScript,
    SaveTemplate,
    SetPreferences,
    SwitchDatabase,
    TestConnection,
} from '../../../wailsjs/go/app/App';
import type { AppApiGateway, ConnectionRuntimeState } from './types';

export const wailsGateway: AppApiGateway = {
    Connect,
    Disconnect,
    Reconnect,
    SwitchDatabase,
    LoadConnections,
    LoadDatabasesForProfile,
    SaveConnection,
    TestConnection,
    GetConnectionStatus: () => GetConnectionStatus() as unknown as Promise<ConnectionRuntimeState>,

    ExecuteQuery,
    CancelQuery,
    ExplainQuery,
    ExecuteUpdateSync,
    FetchMoreRows,
    FetchTotalRowCount,
    FormatSQL,
    CompareQueries,
    ExportCSV,
    ExportJSON,
    ExportSQLInsert,

    BeginTransaction,
    CommitTransaction,
    RollbackTransaction,
    GetTransactionStatus,

    FetchDatabaseSchema,
    FetchTableColumns,
    FetchTableRelationships,
    CreateTable,
    DropObject,
    GetTableDDL,
    AlterTableColumn,
    AddTableColumn,
    DropTableColumn,
    GetIndexes,
    CreateIndex,
    DropIndex,

    GetPreferences,
    SetPreferences,
    CheckForUpdates,

    GetHistory,
    ClearHistory,
    LoadTemplates,
    SaveTemplate,
    DeleteTemplate,
    GetScripts,
    GetScriptContent,
    SaveScript,
    DeleteScript,
    GetBookmarks,
    SaveBookmark,
    DeleteBookmark,

    ForceQuit,
    ConnectProjectEnvironment,
};
