// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {models} from '../models';
import {app} from '../models';
import {utils} from '../models';
import {core} from '../models';
import {plugin} from '../models';

export function ActivateLicense(arg1:string,arg2:string):Promise<license.State>;

export function AddPrimaryKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function AddTableColumn(arg1:string,arg2:string,arg3:models.ColumnDef):Promise<void>;

export function AlterTableColumn(arg1:string,arg2:string,arg3:models.ColumnDef,arg4:models.ColumnDef):Promise<void>;

export function BeginTransaction():Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<app.UpdateInfo>;

export function ClearHistory():Promise<void>;

export function CommitTransaction():Promise<void>;

export function CompareQueries(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:string):Promise<void>;

export function ConnectProjectEnvironment(arg1:string):Promise<void>;

export function CreateCheckConstraint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateForeignKey(arg1:string,arg2:string,arg3:string,arg4:app.ForeignKeyInfo):Promise<void>;

export function CreateIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function CreateProject(arg1:models.Project):Promise<models.Project>;

export function CreateTable(arg1:string,arg2:string,arg3:string,arg4:Array<models.ColumnDef>):Promise<void>;

export function CreateUniqueConstraint(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function DeactivateLicense(arg1:string):Promise<void>;

export function DeleteBookmark(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteScript(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DisableGitTracking():Promise<void>;

export function Disconnect():Promise<void>;

export function DropCheckConstraint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropForeignKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropObjectAdvanced(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function DropPrimaryKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropTableColumn(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DropUniqueConstraint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EnableGitTracking():Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<void>;

export function ExecuteUpdateSync(arg1:string):Promise<number>;

export function ExplainQuery(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ExportAllCSV(arg1:string,arg2:Array<string>):Promise<string>;

export function ExportAllJSON(arg1:string,arg2:Array<string>):Promise<string>;

export function ExportAllSQLInsert(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function ExportCSV(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function ExportConnectionPackage(arg1:string):Promise<string>;

export function ExportJSON(arg1:Array<string>,arg2:Array<any>):Promise<string>;

export function ExportSQLInsert(arg1:Array<string>,arg2:Array<any>,arg3:string):Promise<string>;

export function FetchDatabaseSchema(arg1:string,arg2:string):Promise<void>;

export function FetchMoreRows(arg1:string,arg2:number):Promise<void>;

export function FetchTableColumns(arg1:string,arg2:string):Promise<Array<models.ColumnDef>>;

export function FetchTableRelationships(arg1:string,arg2:string):Promise<Array<models.TableRelationship>>;

export function FetchTotalRowCount(arg1:string):Promise<number>;

export function ForceQuit():Promise<void>;

export function FormatSQL(arg1:string,arg2:string):Promise<string>;

export function GetActiveProject():Promise<models.Project>;

export function GetBookmarks(arg1:string,arg2:string):Promise<Array<models.Bookmark>>;

export function GetCheckConstraints(arg1:string,arg2:string,arg3:string):Promise<Array<app.CheckConstraintInfo>>;

export function GetCommitFileDiffs(arg1:string):Promise<Array<app.GitCommitFileDiff>>;

export function GetConnectionStatus():Promise<app.ConnectionRuntimeState>;

export function GetCurrentVersion():Promise<string>;

export function GetDefaultProjectStorageRoot():Promise<string>;

export function GetExecutionPolicy(arg1:string):Promise<app.ExecutionPolicy>;

export function GetForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<app.ForeignKeyInfo>>;

export function GetGitCommitDiff(arg1:string):Promise<string>;

export function GetGitPendingChanges():Promise<Array<string>>;

export function GetGitTrackingStatus():Promise<app.GitTrackingStatus>;

export function GetHistory():Promise<Array<models.HistoryEntry>>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<app.IndexInfo>>;

export function GetLicenseState():Promise<license.State>;

export function GetPreferences():Promise<utils.Preferences>;

export function GetPrimaryKey(arg1:string,arg2:string,arg3:string):Promise<app.PrimaryKeyInfo>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetScriptContent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetScripts(arg1:string,arg2:string):Promise<Array<models.SavedScript>>;

export function GetTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTransactionStatus():Promise<string>;

export function GetUniqueConstraints(arg1:string,arg2:string,arg3:string):Promise<Array<app.UniqueConstraintInfo>>;

export function ImportConnectionPackage():Promise<models.ConnectionProfile>;

export function ListDriverDescriptors():Promise<Array<core.DriverDescriptor>>;

export function ListGitTimeline(arg1:number,arg2:string):Promise<Array<app.GitTimelineItem>>;

export function ListPluginByCapability(arg1:string):Promise<Array<plugin.Contribution>>;

export function ListProjects():Promise<Array<models.Project>>;

export function LoadConnections():Promise<Array<models.ConnectionProfile>>;

export function LoadDatabasesForProfile(arg1:string):Promise<Array<string>>;

export function LoadTemplates():Promise<Array<models.Template>>;

export function ManualGitCommit(arg1:string):Promise<app.GitCommitResult>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<models.Project>;

export function OpenProjectFromDirectory(arg1:string):Promise<models.Project>;

export function PickDirectory(arg1:string):Promise<string>;

export function Reconnect():Promise<void>;

export function RefreshLicense(arg1:string):Promise<license.State>;

export function RegisterPluginContribution(arg1:plugin.Contribution):Promise<void>;

export function ReorderTableColumns(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ResolvePluginContribution(arg1:string):Promise<plugin.Contribution|boolean>;

export function RestoreGitCommit(arg1:string):Promise<void>;

export function RollbackTransaction():Promise<void>;

export function RunGitTrackingMigration():Promise<void>;

export function SCCheckoutBranch(arg1:string):Promise<void>;

export function SCCheckoutDetached(arg1:string):Promise<void>;

export function SCCommit(arg1:string):Promise<string>;

export function SCCreateBranch(arg1:string):Promise<void>;

export function SCCreateBranchFrom(arg1:string,arg2:string):Promise<void>;

export function SCGetFileDiffs(arg1:string):Promise<Array<app.GitCommitFileDiff>>;

export function SCGetHistory(arg1:number):Promise<Array<app.SCCommit>>;

export function SCGetStatus():Promise<app.SCStatus>;

export function SCGetWorkingFileDiff(arg1:string,arg2:boolean):Promise<app.GitCommitFileDiff>;

export function SCInitRepo():Promise<void>;

export function SCListBranches():Promise<Array<string>>;

export function SCReadGitIgnore():Promise<string>;

export function SCStageAll():Promise<void>;

export function SCStageFile(arg1:string):Promise<void>;

export function SCUnstageFile(arg1:string):Promise<void>;

export function SCWriteGitIgnore(arg1:string):Promise<void>;

export function SaveBookmark(arg1:string,arg2:string,arg3:models.Bookmark):Promise<void>;

export function SaveConnection(arg1:models.ConnectionProfile):Promise<void>;

export function SaveProject(arg1:models.Project):Promise<models.Project>;

export function SaveScript(arg1:models.SavedScript,arg2:string):Promise<void>;

export function SaveTemplate(arg1:models.Template):Promise<void>;

export function SetPreferences(arg1:utils.Preferences):Promise<void>;

export function Shutdown():Promise<void>;

export function SnapshotStoredProcedures(arg1:string):Promise<number>;

export function StartFetchTotalRowCount(arg1:string,arg2:number):Promise<void>;

export function SwitchDatabase(arg1:string):Promise<void>;

export function TestConnection(arg1:models.ConnectionProfile):Promise<void>;

export function TruncateTable(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function UpdateForeignKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:app.ForeignKeyInfo):Promise<void>;
