// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1, arg2) {
  return window['go']['app']['App']['ActivateLicense'](arg1, arg2);
}

export function AddTableColumn(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddTableColumn'](arg1, arg2, arg3);
}

export function AlterTableColumn(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AlterTableColumn'](arg1, arg2, arg3, arg4);
}

export function BeginTransaction() {
  return window['go']['app']['App']['BeginTransaction']();
}

export function CancelQuery(arg1) {
  return window['go']['app']['App']['CancelQuery'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function CommitTransaction() {
  return window['go']['app']['App']['CommitTransaction']();
}

export function CompareQueries(arg1, arg2) {
  return window['go']['app']['App']['CompareQueries'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function ConnectProjectEnvironment(arg1) {
  return window['go']['app']['App']['ConnectProjectEnvironment'](arg1);
}

export function CreateIndex(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['CreateIndex'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function CreateTable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateTable'](arg1, arg2, arg3, arg4);
}

export function DeactivateLicense(arg1) {
  return window['go']['app']['App']['DeactivateLicense'](arg1);
}

export function DeleteBookmark(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteBookmark'](arg1, arg2, arg3);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteScript(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteScript'](arg1, arg2, arg3);
}

export function DeleteTemplate(arg1) {
  return window['go']['app']['App']['DeleteTemplate'](arg1);
}

export function DisableGitTracking() {
  return window['go']['app']['App']['DisableGitTracking']();
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function DropObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DropObject'](arg1, arg2, arg3, arg4);
}

export function DropTableColumn(arg1, arg2, arg3) {
  return window['go']['app']['App']['DropTableColumn'](arg1, arg2, arg3);
}

export function EnableGitTracking() {
  return window['go']['app']['App']['EnableGitTracking']();
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['app']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExecuteUpdateSync(arg1) {
  return window['go']['app']['App']['ExecuteUpdateSync'](arg1);
}

export function ExplainQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExplainQuery'](arg1, arg2, arg3);
}

export function ExportAllCSV(arg1, arg2) {
  return window['go']['app']['App']['ExportAllCSV'](arg1, arg2);
}

export function ExportAllJSON(arg1, arg2) {
  return window['go']['app']['App']['ExportAllJSON'](arg1, arg2);
}

export function ExportAllSQLInsert(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportAllSQLInsert'](arg1, arg2, arg3);
}

export function ExportCSV(arg1, arg2) {
  return window['go']['app']['App']['ExportCSV'](arg1, arg2);
}

export function ExportConnectionPackage(arg1) {
  return window['go']['app']['App']['ExportConnectionPackage'](arg1);
}

export function ExportJSON(arg1, arg2) {
  return window['go']['app']['App']['ExportJSON'](arg1, arg2);
}

export function ExportSQLInsert(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportSQLInsert'](arg1, arg2, arg3);
}

export function FetchDatabaseSchema(arg1, arg2) {
  return window['go']['app']['App']['FetchDatabaseSchema'](arg1, arg2);
}

export function FetchMoreRows(arg1, arg2) {
  return window['go']['app']['App']['FetchMoreRows'](arg1, arg2);
}

export function FetchTableColumns(arg1, arg2) {
  return window['go']['app']['App']['FetchTableColumns'](arg1, arg2);
}

export function FetchTableRelationships(arg1, arg2) {
  return window['go']['app']['App']['FetchTableRelationships'](arg1, arg2);
}

export function FetchTotalRowCount(arg1) {
  return window['go']['app']['App']['FetchTotalRowCount'](arg1);
}

export function ForceQuit() {
  return window['go']['app']['App']['ForceQuit']();
}

export function FormatSQL(arg1, arg2) {
  return window['go']['app']['App']['FormatSQL'](arg1, arg2);
}

export function GetActiveProject() {
  return window['go']['app']['App']['GetActiveProject']();
}

export function GetBookmarks(arg1, arg2) {
  return window['go']['app']['App']['GetBookmarks'](arg1, arg2);
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetCurrentVersion() {
  return window['go']['app']['App']['GetCurrentVersion']();
}

export function GetDefaultProjectStorageRoot() {
  return window['go']['app']['App']['GetDefaultProjectStorageRoot']();
}

export function GetExecutionPolicy(arg1) {
  return window['go']['app']['App']['GetExecutionPolicy'](arg1);
}

export function GetGitCommitDiff(arg1) {
  return window['go']['app']['App']['GetGitCommitDiff'](arg1);
}

export function GetGitPendingChanges() {
  return window['go']['app']['App']['GetGitPendingChanges']();
}

export function GetGitTrackingStatus() {
  return window['go']['app']['App']['GetGitTrackingStatus']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function GetLicenseState() {
  return window['go']['app']['App']['GetLicenseState']();
}

export function GetPreferences() {
  return window['go']['app']['App']['GetPreferences']();
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetScriptContent(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetScriptContent'](arg1, arg2, arg3);
}

export function GetScripts(arg1, arg2) {
  return window['go']['app']['App']['GetScripts'](arg1, arg2);
}

export function GetTableDDL(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTableDDL'](arg1, arg2, arg3);
}

export function GetTransactionStatus() {
  return window['go']['app']['App']['GetTransactionStatus']();
}

export function ImportConnectionPackage() {
  return window['go']['app']['App']['ImportConnectionPackage']();
}

export function ListDriverDescriptors() {
  return window['go']['app']['App']['ListDriverDescriptors']();
}

export function ListGitTimeline(arg1, arg2) {
  return window['go']['app']['App']['ListGitTimeline'](arg1, arg2);
}

export function ListPluginByCapability(arg1) {
  return window['go']['app']['App']['ListPluginByCapability'](arg1);
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function LoadConnections() {
  return window['go']['app']['App']['LoadConnections']();
}

export function LoadDatabasesForProfile(arg1) {
  return window['go']['app']['App']['LoadDatabasesForProfile'](arg1);
}

export function LoadTemplates() {
  return window['go']['app']['App']['LoadTemplates']();
}

export function ManualGitCommit(arg1) {
  return window['go']['app']['App']['ManualGitCommit'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['app']['App']['OpenProject'](arg1);
}

export function OpenProjectFromDirectory(arg1) {
  return window['go']['app']['App']['OpenProjectFromDirectory'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['app']['App']['PickDirectory'](arg1);
}

export function Reconnect() {
  return window['go']['app']['App']['Reconnect']();
}

export function RefreshLicense(arg1) {
  return window['go']['app']['App']['RefreshLicense'](arg1);
}

export function RegisterPluginContribution(arg1) {
  return window['go']['app']['App']['RegisterPluginContribution'](arg1);
}

export function ReorderTableColumns(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReorderTableColumns'](arg1, arg2, arg3);
}

export function ResolvePluginContribution(arg1) {
  return window['go']['app']['App']['ResolvePluginContribution'](arg1);
}

export function RollbackTransaction() {
  return window['go']['app']['App']['RollbackTransaction']();
}

export function RunGitTrackingMigration() {
  return window['go']['app']['App']['RunGitTrackingMigration']();
}

export function SaveBookmark(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveBookmark'](arg1, arg2, arg3);
}

export function SaveConnection(arg1) {
  return window['go']['app']['App']['SaveConnection'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['app']['App']['SaveProject'](arg1);
}

export function SaveScript(arg1, arg2) {
  return window['go']['app']['App']['SaveScript'](arg1, arg2);
}

export function SaveTemplate(arg1) {
  return window['go']['app']['App']['SaveTemplate'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['app']['App']['SetPreferences'](arg1);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function SnapshotStoredProcedures(arg1) {
  return window['go']['app']['App']['SnapshotStoredProcedures'](arg1);
}

export function SwitchDatabase(arg1) {
  return window['go']['app']['App']['SwitchDatabase'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['app']['App']['TestConnection'](arg1);
}
